### ISSUE TITLE
fluids in crafting recipes not working

### ISSUE THREAD

**Issue by QuImUfu** [buttilda/ZZZZZ-Custom-Configs#14]
Config (the part that differs from the original):

``` XML
<shaped>
    <output>minecraft:diamond_sword 1 0</output>
    <row1>"x x"</row1>
    <row2>" x "</row2>
    <row3>" x "</row3>
    <x>water 1000</x>
</shaped>
```

produces this crash:
http://paste.ee/p/ndt6B
Lava also produces this crash
Have i done something wrong or is this a bug in the mod?

**Comment by buttilda** [comment]
You forgot the /output :)

``` XML
<shaped>
    <output>minecraft:diamond_sword 1 0</output>
        <row1>"x x"</row1>
        <row2>" x "</row2>
        <row3>" x "</row3>
        <x>water 1000</x>
    </output>
</shaped>
```

**Comment by buttilda** [comment]
Wait, now that I've looked properly at this...
That won't work even if you fix the syntax. You can't put fluids in a crafting table =P

**Comment by QuImUfu** [comment]
I thought it is for adding fluids to recipes without consuming the bucket^^.  
i should have tried using the bucket item. 
Wow, i feel dumb now.

and btw my syntax is correct, yours isn't. :D 
thanks for the fast answer and your help,

QuImUfu

**Comment by buttilda** [comment]
Yeah, it doesn't work like that unfortunately. You'll have to use the actual water bucket item :)

And yeah, your syntax is correct XD and mine isn't XD I don't know what was going through my head, my apologies XD
