### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xJon** [buttilda/ZZZZZ-Custom-Configs#3]
Is the mod server-side?
if not, can you make it be server-side?

**Comment by buttilda** [comment]
It is server side :)
But it also needs to be present on the client, and the config files should be the same or you could end up with nasty recipe bugs.

**Comment by xJon** [comment]
So, you need to have both mods on server and on client?
mm..
I am looking for a Forge mod that can config just a server, so I will be able to remove recipes only in the server it self, and not in the client. :)

**Comment by buttilda** [comment]
You won't find anything like that.
Recipes need to be registered on both the client and server in order for them to work.

**Comment by xJon** [comment]
Okay.
thanks!
