### ISSUE TITLE
oredict not applying to exnihilo blocks.

### ISSUE THREAD

**Issue by ghost** [buttilda/ZZZZZ-Custom-Configs#8]
Hello.

Adding an oredict entry to an exnihilo/exastris block results in an error.

My intention was to add the ore block oredict entries so that mekanism can process exnihilos ore gravel/sand/dust which in turn offers ore doubling.

OreDictionary.xml http://pastebin.com/5kU4749D
Stacks 1 - 3 do not apply. Stack 4 does.

Console error: http://pastebin.com/J6ELKW4n

Complete log: http://pastebin.com/5gXek82i

Edit:
Forgot to mention that I also tried the same using minetweaker and that too failed to add the entries to said blocks.

**Comment by buttilda** [comment]
Make sure you are using the latest recommended Forge.
There has been some internal changes to the OreDictionary, maybe you have an unstable version.

**Comment by ghost** [comment]
Recommended is currently build 1448 which I am indeed running.

**Comment by buttilda** [comment]
Seems to be related to the load order of mods. Easy fix!
